matrix:
  include:
    - language:  php
      php: 5.6
      install:
       - composer install
       - mkdir -p build/logs
       - ./vendor/phpunit/phpunit/phpunit --coverage-clover ./tests/logs/clover.xml ./tests/
      before_script:
        - find . -type f -name *.php -not -path "./vendor/*" | xargs -n1 php -l
      script:        
       - cd ${TRAVIS_BUILD_DIR}
       - phpunit --configuration="tests/phpunit.xml" --include-path="tests/"
       - cat build/logs/clover.xml
      after_script:
       - php vendor/bin/php-coveralls
    - language: markdown
      addons:
        apt:
          packages:
            - aspell
            - aspell-fr
      script:
        - gem install mdl
        - cd ${TRAVIS_BUILD_DIR}
        - ./tests/tools/setCustomMDWarnings.sh 
        - mdl -r $MDLWAR *.md docs/fr_FR/*.md
        - ./tests/tools/spellCheckMD.sh 