matrix:
  include:
    - language:  php
      php: 5.6
      before_install:
      - composer require phpunit/phpunit:4.8.* satooshi/php-coveralls:dev-master
      - composer install --dev
      before_script:
          - find . -type f -name *.php | xargs -n1 php -l
      script:        
          - cd ${TRAVIS_BUILD_DIR}
          - phpunit --configuration="tests/phpunit.xml" --include-path="tests/"
          - ./vendor/bin/phpunit --coverage-clover ./tests/logs/clover.xml --include-path="tests/"
      after_script:
      - php vendor/bin/coveralls -v

    - language: markdown
      addons:
        apt:
          packages:
            - aspell
            - aspell-fr
      script:
        - gem install mdl
        - cd ${TRAVIS_BUILD_DIR}
        - ./tests/tools/setCustomMDWarnings.sh 
        - mdl -r $MDLWAR *.md docs/fr_FR/*.md
        - ./tests/tools/spellCheckMD.sh 