matrix:
  include:
    - language:  php
      php: 5.6
      install:
       - composer install
       - mkdir -p build/logs
      before_script:
        - find . -type f -name *.php -not -path "./vendor/*" | xargs -n1 php -l
      script:        
       - cd ${TRAVIS_BUILD_DIR}
       - ./vendor/phpunit/phpunit/phpunit --coverage-clover ./build/logs/clover.xml --whitelist "core desktop" ./tests/
       - ls -alR build
       - rm -fr build/logs/*
       - ./vendor/phpunit/phpunit/phpunit --coverage-clover ./build/logs/clover.xml --whitelist core --whitelist desktop ./tests/
       - ls -alR build
       - rm -fr build/logs/*
       - phpunit --configuration="tests/phpunit.xml"
       - ls -alR build
       - rm -fr build/logs/*
       - phpunit --configuration="tests/phpunit2.xml"
       - ls -alR build
       - rm -fr build/logs/*
       - phpunit --configuration="tests/phpunit3.xml"
       - ls -alR build
       - rm -fr build/logs/*
       - ./vendor/phpunit/phpunit/phpunit --configuration="tests/phpunit.xml"
       - ls -alR build
       - rm -fr build/logs/*
       - ./vendor/phpunit/phpunit/phpunit --configuration="tests/phpunit2.xml"
       - ls -alR build
       - rm -fr build/logs/*
       - ./vendor/phpunit/phpunit/phpunit --configuration="tests/phpunit3.xml"
       - ls -alR build
       - rm -fr build/logs/*
      after_script:
       - php vendor/bin/php-coveralls
    - language: markdown
      addons:
        apt:
          packages:
            - aspell
            - aspell-fr
      script:
        - gem install mdl
        - cd ${TRAVIS_BUILD_DIR}
        - ./tests/tools/setCustomMDWarnings.sh 
        - mdl -r $MDLWAR *.md docs/fr_FR/*.md
        - ./tests/tools/spellCheckMD.sh 