matrix:
  include:
    - language:  php
      php: 5.6
      before_script:
          - find . -type f -name *.php | xargs -n1 php -l
      script:        
          - cd ${TRAVIS_BUILD_DIR}
          - phpunit --configuration="tests/phpunit.xml" --include-path="tests/"

    - language: markdown
      addons:
        apt:
          packages:
            - aspell
            - aspell-fr
      script:
        - gem install mdl
        - cd ${TRAVIS_BUILD_DIR}
        - ./tests/tools/setCustomMDWarnings.sh 
        - mdl -r $MDLWAR *.md docs/fr_FR/*.md
        - ./tests/tools/spellCheckMD.sh 